version: "3.8"
services:
  postgres:
    container_name: memowave_postgres_container
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_DB: "memowave_db"
      POSTGRES_USER: "pgadmin"
      POSTGRES_PASSWORD: "pgadmin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d database" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: 1G
    networks:
      - memowave-network

  liquibase:
    container_name: memowave_liquibase_container
    image: liquibase/liquibase:4.32.0
    environment:
      LIQUIBASE_COMMAND_URL: "jdbc:postgresql://postgres:5432/memowave_db"
      LIQUIBASE_COMMAND_DRIVER: "org.postgresql.Driver"
      LIQUIBASE_COMMAND_USERNAME: "pgadmin"
      LIQUIBASE_COMMAND_PASSWORD: "pgadmin"
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog.yml # Path within the container
      LIQUIBASE_SEARCH_PATH: /liquibase/changelog
    command: update # Command to execute (e.g., update, rollback)
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
    networks:
      - memowave-network
    depends_on:
      postgres:
        condition: service_healthy # Ensure DB is ready before Liquibase runs

  pgadmin:
    container_name: memowave_pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mail.me"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80/misc/ping || exit -1" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - memowave-network
    depends_on:
      postgres:
        condition: service_healthy # Ensure DB is ready before Liquibase runs

  userservice:
    container_name: user-management-service
    build:
      dockerfile_inline: |
        # Родительский образ контейнера с java внутри
        FROM eclipse-temurin:21-jre-alpine
        RUN mkdir /app
        WORKDIR /app
        # Копирование jar-файла в контейнер
        COPY module-user-management/build/libs/*-0.0.1-SNAPSHOT.jar /app.jar
        # Открытие порта 8081
        EXPOSE 8081
        USER 1000:1000
        # Команда, которая будет запущена при старте контейнера java -jar ./app.jar
        ENTRYPOINT ["java", "-jar", "/app.jar"]
    environment:
      SERVICE_PORT: 8081
      DB_URL: jdbc:postgresql://postgres:5432/memowave_db
      DB_USERNAME: pgadmin
      DB_PASSWORD: pgadmin
    ports:
      - "8081:8081"
#    restart: unless-stopped
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://user-management-service:8081/actuator/health" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
    networks:
      - memowave-network
    depends_on:
      postgres:
        condition: service_healthy

  gateway:
    container_name: gateway-service
    build:
      dockerfile_inline: |
        # Родительский образ контейнера с java внутри
        FROM eclipse-temurin:21-jre-alpine
        RUN mkdir /app
        WORKDIR /app
        # Копирование jar-файла в контейнер
        COPY module-gateway/build/libs/*-0.0.1-SNAPSHOT.jar /app.jar
        # Открытие порта 8080
        EXPOSE 8080
        USER 1000:1000
        # Команда, которая будет запущена при старте контейнера java -jar ./app.jar
        ENTRYPOINT ["java", "-jar", "/app.jar"]
#    depends_on:
#      userservice:
#        condition: service_healthy
    environment:
      SERVICE_PORT: 8080
      USER_MANAGEMENT_URL: "http://user-management-service:8081"
    ports:
      - "8080:8080"
#    restart: unless-stopped
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://gateway-service:8080/actuator/health" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
    networks:
      - memowave-network

volumes:
  database-data:
  pgadmin-data:

networks:
  memowave-network:
    driver: bridge
