version: "3.9"

name: "memowave"

services:
  postgres:
    container_name: memowave_postgres_container
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_DB: "memowave_db"
      POSTGRES_USER: "pgadmin"
      POSTGRES_PASSWORD: "pgadmin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d database" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - memowave-network

  liquibase:
    container_name: memowave_liquibase_container
    image: liquibase/liquibase:4.32.0
    environment:
      LIQUIBASE_COMMAND_URL: "jdbc:postgresql://postgres:5432/memowave_db"
      LIQUIBASE_COMMAND_DRIVER: "org.postgresql.Driver"
      LIQUIBASE_COMMAND_USERNAME: "pgadmin"
      LIQUIBASE_COMMAND_PASSWORD: "pgadmin"
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog.yml # Path within the container
      LIQUIBASE_SEARCH_PATH: /liquibase/changelog
    command: update # Command to execute (e.g., update, rollback)
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
    networks:
      - memowave-network
    depends_on:
      postgres:
        condition: service_healthy # Ensure DB is ready before Liquibase runs

  minio:
    image: minio/minio
    container_name: minio
#    ports:
#      - "9000:9000"
#      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - memowave-network

  rabbitmq:
    # Use the official image with the management plugin enabled
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
#    ports:
      # AMQP protocol port (for your applications to connect)
#      - "5672:5672"
      # HTTP management UI port (access via http://localhost:15672)
#      - "15672:15672"
    environment:
      # Optional: set custom default user and password (default is guest/guest)
      RABBITMQ_DEFAULT_USER: rbuser
      RABBITMQ_DEFAULT_PASS: rbuser
    volumes:
      # Optional: Persist data to a local volume to prevent data loss on container restart
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/
    networks:
      - memowave-network

  configuration:
    container_name: configuration-service
    build:
      context: ./module-configuration
      dockerfile: ./Dockerfile
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://configuration-service:8080/actuator/health" ]
      interval: 24h
      start_period: 25s
      start_interval: 5s
    networks:
      - memowave-network

  discovery:
    container_name: discovery-service
    build:
      context: ./module-discovery
      dockerfile: ./Dockerfile
    environment:
      CONFIGURATION_HOST: configuration-service
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://discovery-service:8080/actuator/health" ]
      interval: 24h
      start_period: 25s
      start_interval: 5s
    depends_on:
      configuration:
        condition: service_healthy
    networks:
      - memowave-network

  userservice:
    container_name: user-management-service
    build:
      context: ./module-user-management
      dockerfile: ./Dockerfile
    environment:
      CONFIGURATION_HOST: configuration-service
      DB_URL: jdbc:postgresql://postgres:5432/memowave_db
      DB_USERNAME: pgadmin
      DB_PASSWORD: pgadmin
      SMTP_HOST: fakesmtp
      SMTP_PORT: 1025
      EMAIL_USERNAME: admin@mail.me
      EMAIL_PASSWORD: admin
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://user-management-service:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - memowave-network
    depends_on:
      configuration:
        condition: service_healthy
      discovery:
        condition: service_started
      postgres:
        condition: service_healthy

  importexportservice:
    container_name: import-export-service
    build:
      context: ./module-import-export
      dockerfile: ./Dockerfile
    environment:
      CONFIGURATION_HOST: configuration-service
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_BUCKET: "output-files"
      RABBIT_HOST: "rabbitmq"
      RABBIT_PORT: "5672"
      RABBIT_USERNAME: "rbuser"
      RABBIT_PASSWORD: "rbuser"
      RABBIT_INPUT_QUEUE: "message_queue_upload"
      RABBIT_OUTPUT_QUEUE: "message_queue_process"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://import-export-service:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - memowave-network
    depends_on:
      configuration:
        condition: service_healthy
      discovery:
        condition: service_started
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  webuiservice:
    container_name: web-ui-service
    build:
      context: ./module-web-ui
      dockerfile: ./Dockerfile
    environment:
      CONFIGURATION_HOST: configuration-service
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_BUCKET: "input-files"
      RABBIT_HOST: "rabbitmq"
      RABBIT_PORT: "5672"
      RABBIT_USERNAME: "rbuser"
      RABBIT_PASSWORD: "rbuser"
      RABBIT_INPUT_QUEUE: "message_queue_process"
      RABBIT_OUTPUT_QUEUE: "message_queue_upload"
    ports:
      - "8084:8080"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://web-ui-service:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - memowave-network
    depends_on:
      configuration:
        condition: service_healthy
      discovery:
        condition: service_started
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  exerciseservice:
    container_name: exercise-service
    build:
      context: ./module-exercise
      dockerfile: ./Dockerfile
    environment:
      CONFIGURATION_HOST: configuration-service
      DB_URL: jdbc:postgresql://postgres:5432/memowave_db
      DB_USERNAME: pgadmin
      DB_PASSWORD: pgadmin
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://exercise-service:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - memowave-network
    depends_on:
      configuration:
        condition: service_healthy
      discovery:
        condition: service_started
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  gateway:
    container_name: gateway-service
    build:
      context: ./module-gateway
      dockerfile: ./Dockerfile
    environment:
      CONFIGURATION_HOST: configuration-service
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://gateway-service:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - memowave-network
    depends_on:
      configuration:
        condition: service_healthy
      discovery:
        condition: service_started
      userservice:
        condition: service_started
      exerciseservice:
        condition: service_started

  fakesmtp:
    container_name: fake-smtp-server
    image: haravich/fake-smtp-server:latest
    ports:
#      - "1025:1025"
      - "1080:1080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - memowave-network

volumes:
  database-data:
  pgadmin-data:
  minio_data:
  rabbitmq_data:

networks:
  memowave-network:
    driver: bridge
