spring:
  application:
    name: exercise-service
  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    fetchRegistry: true
    service-url:
      defaultZone: http://discovery-service:8080/eureka
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    metadataMap:
      management.context-path: /

springdoc:
  api-docs:
    path: /exercise-service/v3/api-docs