server:
  port: ${SERVICE_PORT:8080}
spring:
  application:
    name: module-gateway
  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: module-user-management
              uri: http://localhost:8080
              predicates:
                - Path=/actuator,/api/auth/sign/*
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"