server:
  port: ${SERVICE_PORT:8080}
spring:
  application:
    name: module-gateway
  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: user-management-service
              uri: ${USER_MANAGEMENT_URL}
              predicates:
                - Path=/user-management-service/**,/api/users/**,/api/auth/*
            - id: import-export-service
              uri: ${IMPORT_EXPORT_URL}
              predicates:
                - Path=/import-export-service/**,/api/import/**
            - id: exercise-service
              uri: ${EXERCISE_URL}
              predicates:
                - Path=/exercise-service/**,/api/words/**
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    urls:
      - name: user-management-service
        url: /user-management-service/v3/api-docs
      - name: import-export-service
        url: /import-export-service/v3/api-docs
      - name: exercise-service
        url: /exercise-service/v3/api-docs